### ISSUE TITLE
Add the .gitignore file 

### ISSUE THREAD

**Issue by GeorgeZargaryan** [MaehRia/Obsidian-Repo#1]
**As you know**, some files in Obsidian are changing during our work process. 
They're located in the .obsidian folder. Via adding this folder / certain files to .gitignore file will make git not to push this data into your repository. 

After this, you can use:

```sh
git rm --cached filename
```

to remove existing files from your git repo.

**Comment by MaehRia** [comment]
Task is done. Unwanted files are removed from the repository. Thanks for assisting in this process.

**Comment by MaehRia** [comment]
See you in next task.
